/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author carob8920
 */
public class familyBudget extends javax.swing.JFrame {
 double housing, transportation, life, savings, income; 
 double housingPc, transportPc, lifePc, savingsPc; 
 String transportB = "";
 String housingB = "";
 String lifeB = "";
 String savingsB = "";

    /**
     * Creates new form familyBudget
     */
    public familyBudget() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        subtitleLabel = new javax.swing.JLabel();
        housingLabel = new javax.swing.JLabel();
        transportationLabel = new javax.swing.JLabel();
        lifeLabel = new javax.swing.JLabel();
        savingsLabel = new javax.swing.JLabel();
        incomeLabel = new javax.swing.JLabel();
        housingTF = new javax.swing.JTextField();
        transportationTF = new javax.swing.JTextField();
        lifeTF = new javax.swing.JTextField();
        savingsTF = new javax.swing.JTextField();
        incomeTF = new javax.swing.JTextField();
        calculateButton = new javax.swing.JButton();
        middlePanel = new javax.swing.JPanel();
        housingLabel2 = new javax.swing.JLabel();
        transportationLabel2 = new javax.swing.JLabel();
        lifeLabel2 = new javax.swing.JLabel();
        savingsLabel2 = new javax.swing.JLabel();
        bottomPanel = new javax.swing.JPanel();
        housingResponse = new javax.swing.JLabel();
        transportationResponse = new javax.swing.JLabel();
        lifeResponse = new javax.swing.JLabel();
        savingsResponse = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        topPanel.setBackground(new java.awt.Color(255, 204, 255));

        titleLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        titleLabel.setText("Family budget planner");

        subtitleLabel.setText("Enter the amount of money you spend in each category per month");

        housingLabel.setText("Housing:");

        transportationLabel.setText("Transportation:");

        lifeLabel.setText("Life:");

        savingsLabel.setText("Savings:");

        incomeLabel.setText("Enter your monthly net income:");

        calculateButton.setText("Calculate");
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleLabel)
                .addGap(130, 130, 130))
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subtitleLabel)
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addComponent(incomeLabel)
                        .addGap(18, 18, 18)
                        .addComponent(incomeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(housingLabel)
                            .addGroup(topPanelLayout.createSequentialGroup()
                                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(topPanelLayout.createSequentialGroup()
                                        .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(transportationLabel)
                                            .addComponent(lifeLabel)
                                            .addComponent(savingsLabel))
                                        .addGap(55, 55, 55)
                                        .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lifeTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                            .addComponent(transportationTF, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(savingsTF)))
                                    .addComponent(housingTF, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                                .addComponent(calculateButton)))))
                .addGap(47, 47, 47))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subtitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(housingLabel)
                            .addComponent(housingTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(transportationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(transportationTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lifeLabel)
                            .addComponent(lifeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(savingsLabel)
                            .addComponent(savingsTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(incomeLabel)
                            .addComponent(incomeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                        .addComponent(calculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        middlePanel.setBackground(new java.awt.Color(204, 255, 204));

        housingLabel2.setText("Housing:");

        transportationLabel2.setText("Transportation:");

        lifeLabel2.setText("Life:");

        savingsLabel2.setText("Savings:");

        javax.swing.GroupLayout middlePanelLayout = new javax.swing.GroupLayout(middlePanel);
        middlePanel.setLayout(middlePanelLayout);
        middlePanelLayout.setHorizontalGroup(
            middlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(middlePanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(middlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(middlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lifeLabel2)
                        .addComponent(savingsLabel2))
                    .addComponent(transportationLabel2)
                    .addComponent(housingLabel2))
                .addContainerGap(306, Short.MAX_VALUE))
        );
        middlePanelLayout.setVerticalGroup(
            middlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(middlePanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(housingLabel2)
                .addGap(18, 18, 18)
                .addComponent(transportationLabel2)
                .addGap(18, 18, 18)
                .addComponent(lifeLabel2)
                .addGap(18, 18, 18)
                .addComponent(savingsLabel2)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        bottomPanel.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout bottomPanelLayout = new javax.swing.GroupLayout(bottomPanel);
        bottomPanel.setLayout(bottomPanelLayout);
        bottomPanelLayout.setHorizontalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(bottomPanelLayout.createSequentialGroup()
                        .addComponent(housingResponse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
                    .addComponent(transportationResponse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lifeResponse, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                    .addComponent(savingsResponse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bottomPanelLayout.setVerticalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(housingResponse, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transportationResponse, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lifeResponse, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(savingsResponse, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(middlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bottomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(middlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bottomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
        
//         String housingBar, transportBar, lifeBar, savingsBar;

         
        housing = Double.parseDouble(housingTF.getText());
        transportation = Double.parseDouble(transportationTF.getText());
        life = Double.parseDouble(lifeTF.getText());
        savings = Double.parseDouble(savingsTF.getText());
        income = Double.parseDouble(incomeTF.getText());
        
        housingPc = (housing*100)/income;
        transportPc = (transportation*100)/income;
        lifePc = (life*100)/income;
        savingsPc = (savings*100)/income;
        
        housingLabel2.setText("Housing: "+housingPc+"%");
        transportationLabel2.setText("Transportation: "+transportPc+"%");
        lifeLabel2.setText("Life: "+lifePc+"%");
        savingsLabel2.setText("Savings: "+savingsPc+"%");
        
//        failed attempt at bars
//        for (int i=0; i< housingPc ; i++){
//            housingB += " ";
//            housingLabel2.setText(housingB);  
//        }
//        
//        for (int a=0; a< transportPc; a++){
//            transportB += " ";
//            System.out.println(a);
//            transportationLabel2.setText(transportB);
//        }
//        for (int b=0; b < lifePc; b++){
//            lifeB +=" ";
//            lifeLabel2.setText(lifeB);
//        }
//        for (int c=0; c < savingsPc; c++){
//            savingsB += " ";
//            savingsLabel2.setText(savingsB);
//        }
//        
        
        if (housingPc > 35){ //housing rule (no more than 35%
            housingResponse.setText("Warning! You are spending too much on housing.");
        } else {
            housingResponse.setText("Your spendings on housing is fine.");
        }
        
        if (transportPc > 15){ //transport rule (no more than 15%
            transportationResponse.setText("Warning! You are spending too much on transportation.");
        } else {
            transportationResponse.setText("Your spendings on transportation are fine.");
        }
        
        if (lifePc > 25){ //life rule no more than 25%
            lifeResponse.setText("Warning! You are spending too much on life.");
        } else {
            lifeResponse.setText("Your spendings on life are fine.");
        }
        
        if (savingsPc < 10){ //savings rules no less than 10%
            savingsResponse.setText("Warning! You are not saving enough for the future.");
        } else {
            savingsResponse.setText("Your savings are fine.");
        }
        
    }//GEN-LAST:event_calculateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(familyBudget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(familyBudget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(familyBudget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(familyBudget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new familyBudget().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JButton calculateButton;
    private javax.swing.JLabel housingLabel;
    private javax.swing.JLabel housingLabel2;
    private javax.swing.JLabel housingResponse;
    private javax.swing.JTextField housingTF;
    private javax.swing.JLabel incomeLabel;
    private javax.swing.JTextField incomeTF;
    private javax.swing.JLabel lifeLabel;
    private javax.swing.JLabel lifeLabel2;
    private javax.swing.JLabel lifeResponse;
    private javax.swing.JTextField lifeTF;
    private javax.swing.JPanel middlePanel;
    private javax.swing.JLabel savingsLabel;
    private javax.swing.JLabel savingsLabel2;
    private javax.swing.JLabel savingsResponse;
    private javax.swing.JTextField savingsTF;
    private javax.swing.JLabel subtitleLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel topPanel;
    private javax.swing.JLabel transportationLabel;
    private javax.swing.JLabel transportationLabel2;
    private javax.swing.JLabel transportationResponse;
    private javax.swing.JTextField transportationTF;
    // End of variables declaration//GEN-END:variables
}
